### ISSUE TITLE
The Color Schemes in MacOS Sierra(10.12) not work

### ISSUE THREAD

**Issue by wang4921** [mbadolato/iTerm2-Color-Schemes#102]
There is only one color in iterm2 although I choose any colortheme. If I choose solarized theme ,it looks like this.
![2017-01-21 10 28 54](https://cloud.githubusercontent.com/assets/11326828/22171228/75961656-dfc4-11e6-945f-1c059501b42f.png)
How can I fix it ?  It looks so strange.

**Comment by mbadolato** [comment]
I don't know what could be happening. I've been using Sierra since it came out without any issues. Can you post a screen shot showing the themes imported (and listed in the dropdown)?

**Comment by wang4921** [comment]
![2017-02-20 11 32 50](https://cloud.githubusercontent.com/assets/11326828/23110985/6ed9a950-f760-11e6-98c7-4d73c1ba3baf.png)
@mbadolato 
Is there any issues that I config theme in the prerferences?

**Comment by mbadolato** [comment]
@wang4921 I'm not sure I understand your question

**Comment by mbadolato** [comment]
The Solorized Dark that you have checked in your screenshot is the version that comes with iTerm (I think). If you want to use the one from this repo, you need to import it and choose it from the list, further down (where the black arrow pointing down is)

**Comment by jarandaf** [comment]
I'm also facing this issue. It looks like any color scheme import takes no effect (at least on Sierra).

**Comment by sebastianbarfurth** [comment]
The import itself takes no effect, you would need to select it from the dropdown after importing it @jarandaf.

**Comment by jarandaf** [comment]
I may not have expressed myself clearly; I did select the scheme after the import @sebastianbarfurth

**Comment by ch-gz** [comment]
Append this to .bashrc or .bash_profile:
`export CLICOLOR=1`

**Comment by fyee** [comment]
it does no efforts , only the background color changed, how can tell me why? 

![image](https://user-images.githubusercontent.com/6078758/29495638-c8bd6136-85f5-11e7-9dd2-5fa1d1b272d4.png)
![image](https://user-images.githubusercontent.com/6078758/29495639-d3487db6-85f5-11e7-8aa2-113ce2fe9ad9.png)

**Comment by ns-njoshi** [comment]
I can't see different colors even after export CLICOLOR=
<img width="961" alt="screen shot 2018-11-19 at 3 17 40 pm" src="https://user-images.githubusercontent.com/43150171/48740957-508e4b00-ec0e-11e8-9248-200fde061a95.png">
1

I can only see blue color and rest all in black. I also managed the contrast setting to 0 as many people were saying that it reduces the color effect

**Comment by Shaunakde** [comment]
I think I am facing the same issue. 

I have the following added to my .bash_profile:
`# Set CLICOLOR if you want Ansi Colors in iTerm2
export CLICOLOR=1

# Set colors to match iTerm2 Terminal Colors
export TERM=xterm-256color`

I have also tried everything mentioned here: https://superuser.com/questions/399594/color-scheme-not-applied-in-iterm2

Nothing seems to be working. I am on MacOS 10.14.1

**Comment by mbadolato** [comment]
@ns-njoshi Are you set to xterm-256 for your terminal type? If you have the CLICOLOR set, I don't know what else it could be. Brogrammer does display properly on my local system (I use that theme all the time)

**Comment by JRSQ1231** [comment]
how do you append the .bash_profile?

**Comment by jabbson** [comment]
@JRSQ1231 `echo "export CLICOLOR=1" >> ~/.bash_profile`
