### ISSUE TITLE
Color space handling incorrect

### ISSUE THREAD

**Issue by amckinlay** [mbadolato/iTerm2-Color-Schemes#106]
I wouldn't doubt if most of the themes in this repository are broken. Currently, iTerm2 supports specifying RGB values in two color spaces in .termcolors files, Generic RGB (default when unspecified) and sRGB (recent addition). Taking a look at the conversion scripts, it seems that neither of them handle the color space specification. In fact, the default Generic RGB color space is mishandled as sRGB by both of the scripts that handle .itermcolors files directly. This will cause colors to be incorrect when converting to *any* of the other terminal emulator formats.

Also, at least a few iTerm2 themes by themselves have incorrect colors. The `ayu.termcolors` (and probably the light version) uses colors from the original Sublime Text theme directly without specifying a color space. Since the Sublime Text colors are sRGB and the default color space for iTerm2 is Generic RGB, the two themes do not match (this includes the background color which is very noticeable). The funny thing is that the MacOS Terminal theme conversion is correct for ayu, since the script treats the values as sRGB (two wrongs make a right).

Finally, it might be a good idea to have all iTerm2 color schemes specify their colors in sRGB since the iTerm2 files are used as a basis for the other themes, which are mostly sRGB. The sRGB (usual color space of the original themes outside of iTerm) -> Generic RGB (how most of the .itermcolors files are specified) -> sRGB (how most other terminal color scheme files are specified) is lossy.

**Comment by mbadolato** [comment]
Thanks for the feedback! Patches welcome 😄
