### ISSUE TITLE
How to contribute my color scheme?

### ISSUE THREAD

**Issue by adoyle-h** [mbadolato/iTerm2-Color-Schemes#109]
I have made a screenshot with 13pt Monaco and no transparency background, and exported a .itermcolors file.
But I do not know how to deal with the Xresources/ konsole/ putty/ xrdb/ ... folders . Should I do anything else?

**Comment by mbadolato** [comment]
There's a script in the `tools` directory called `update_all.py` that should create all of those. If you're not able to run it, that's ok. I typically run it when I add new themes to the repo. 

If you have forked this repo, add your changes and push them to your fork, then submit a PR back to my repo.

Thanks!
