### ISSUE TITLE
[question] - Remmina color schemes

### ISSUE THREAD

**Issue by antenore** [mbadolato/iTerm2-Color-Schemes#124]
First of all thanks or this repository!!!

I've written a color scheme manager for http://github.com/FreeRDP/Remmina, a Gtk+ remote desktop client. It uses, almost, the same color scheme files of termite.

So, for instance, https://github.com/mbadolato/iTerm2-Color-Schemes/blob/master/termite/AtelierSulphurpool , becomes:

```
[ssh_colors]
background = #202746
cursor = #979db4
foreground = #979db4
color0 =  #202746
color1 = #c94922
color2 = #ac9739
color3 = #c08b30
color4 = #3d8fd1
color5 = #6679cc
color6 = #22a2c9
color7 = #979db4
color8 = #6b7394
color9 = #c76b29
color10 = #293256
color11 = #5e6687
color12 = #898ea4
color13 = #dfe2f1
color14 = #9c637a
color15 = #f5f7ff
```

It just change the group name and there are not quotes. So it's quite easy to convert from one to the other.

Would you be interested in a PR with those themes?

**Comment by mbadolato** [comment]
Sure! The more formats, the better! I would just request that the converter be included as well in the `tools/` directory and set up to run as part of the `update_all.py` script!

Thanks!

**Comment by antenore** [comment]
Ok, I'll work on it ASAP.

**Comment by mbadolato** [comment]
👍
