### ISSUE TITLE
[question] - Mac, color schemes dont save 

### ISSUE THREAD

**Issue by ut4utc** [mbadolato/iTerm2-Color-Schemes#133]
Hi,
Thank you for the wonderful themes.
I have a small problem. 
At the time when I open a new tab - there again is the default colors. 
If I open new Tab - I look my Default Profile Color Scheme - Agnoster, but I want look Atom from yours colors.  
What do you need to do to choose the right color after closing iTerm? 

iTerm - latest. 
Oh-My-Zsh config [here](https://proinsurer.com.ua/en/blog-en/avi/181-a-beautifully-productive-terminal-experience-iterm,-oh-my-zsh.html)

**Comment by mbadolato** [comment]
Are you changing the schemes using CMD-I or CMD-,  ?   If you use CMD-I it only changes it in the session window you're currently in but will revert back to the profile's default when you open a new session.  If you use CMD-, (Preferences) and go to the profiles tab and select the color from there, then it will change the scheme permanently for that profile. Also make sure your iterm preferences save when exiting the program (it should be a pop-up, but if not, in the Preferences on the general tab there should be a button for it)

Hope that helps!  If it doesn't and the colors are not saving, there may be something corrupt with your iTerm. try reinstalling or ping George (the iTerm maintainer) on their repo

Cheers!

**Comment by ut4utc** [comment]
You are my God! Thanks a lot. It's realy working niw))) LOL
Really I used the CMD+I, and didn't think about it, oh  !:) 
idk why I cant used CMD+, it's simple oh-la-la, but.. Maybe I'm was stupid

Sometimes this happens when you work a lot and then half a day do not understand why the code is perfect and it does not work. Just put a comma instead of a point)

I'm happy now, thank you Mark!
Cheers!

**Comment by mbadolato** [comment]
Awesome, glad to hear it worked!

Cheers!
