### ISSUE TITLE
Add all Schemes to Webpage

### ISSUE THREAD

**Issue by MinchinWeb** [mbadolato/iTerm2-Color-Schemes#145]
Wonderful collection you have here! Thanks for putting it together.

A number of schemes are missing from the webpage (http://iterm2colorschemes.com/). Would it be possible to add a screenshot of them? Here's the list:

- BlulocoDark
- BlulocoLight
- Builtin Dark
- Builtin Light
- Builtin Pastel Dark
- Builtin Solarized Dark
- Builtin Solarized Light
- Builtin Tango Dark
- Builtin Tango Light
- Calamity
- Elementary
- Fahrenheit
- FirefoxDev
- Firewatch
- ForestBlue
- Gruvbox Dark
- Hacktober
- Monokai Remastered
- Monokai Vivid
- OneHalfDark
- OneHalfLight
- Pandora
- Purple Rain
- Red Planet
- Ryuuko
- Snazzy
- Solarized Dark - Patched
- Tango Adapted
- Tango Half Adapted
- Tomorrow Night Burns
- Ubuntu
- UnderTheSea
- Violet Dark
- Violet Light
- ayu
- ayu_light
- deep
- purplepeter
- synthwave

Kibble is listed, but not alphabetically.

**Comment by mbadolato** [comment]
Yeah I've gotten really lax about keeping that updated. It's been annoying trying to keep that gh-pages branch (the website) in sync with the main repo Readme since I have to cut and paste screen shots and credits 😄 

 Thanks for the reminder! Hopefully I can do it in the coming week.

**Comment by mbadolato** [comment]
They should all be updated now!
