### ISSUE TITLE
Ayu Mirage Theme

### ISSUE THREAD

**Issue by rcreadii** [mbadolato/iTerm2-Color-Schemes#165]
Can ayu's mirage theme be added, it looks amazing! And its easier on the eyes.

**Comment by mbadolato** [comment]
Would love to add it if someone can port the colors over!

**Comment by mbadolato** [comment]
@alebcay added the Ayu and Ayu Light themes. Perhaps they have Mirage as well?

**Comment by alebcay** [comment]
Sorry I haven't seen this, my notifications on GitHub have a very low signal-to-noise ratio. If this isn't done yet, I'll look into it.

**Comment by christopherii** [comment]
No worries! It'd be awesome if this was added

**Comment by christopherii** [comment]
And is it easy to make both the iterm and a terminal port?

**Comment by mbadolato** [comment]
When someone submits new themes that get added, I run the generator tool in the tools directory (update_all I think it's called; it's not in front of me) that creates the various ports files
