### ISSUE TITLE
Add ports for alacritty

### ISSUE THREAD

**Issue by nikeee** [mbadolato/iTerm2-Color-Schemes#177]
Alacritty has support for colors:
https://github.com/jwilm/alacritty

Some schemes are available here:
https://github.com/jwilm/alacritty/wiki/Color-schemes

**Comment by mbadolato** [comment]
Hi thanks for adding. If you or someone else would like to add a conversion script to put them in Alacritty format, I'd be happy to add it! Thanks

**Comment by nikeee** [comment]
Maybe we can use something of this site for conversion:
https://terminal.sexy

Its source is located here: https://github.com/stayradiated/terminal.sexy (MIT licensed)

**Comment by JonathanMH** [comment]
I'd love to take a stab at it, the base or "source" should always be the iTerm format, correct?

**Comment by 8bitkitkat** [comment]
There is a script that creates an alacritty theme from an xresources file although it only does it from the currently loaded xresources file, it could be modified. https://gist.github.com/zacharied/e33300ce340caa70499d516ed8ac8de6
