### ISSUE TITLE
Change schemes folder name

### ISSUE THREAD

**Issue by Glennmen** [mbadolato/iTerm2-Color-Schemes#178]
Not really an issue, just a suggestion.
First time I am on this repo and it took me a while to find the correct folder, I kept overlooking it between the other folders.
I saw the other terminal port folders and was looking for an `iterm` folder.

So my suggestion is to change `schemes` -> `iterm`

**Comment by mbadolato** [comment]
Hi, this originally started as just an iTerm repo then other formats were added. At this point there are too many blogs and tutorials and they link to that folder for the schemes, plus other tools that could be pointing at that directory. At this time I'm going to leave it, but thank you for the suggestion! If yuo'd like to submit a PR with a note in the README file, I'd be happy to include that. A symlink called iTerm pointing to `schemes` could work too
