### ISSUE TITLE
windows & font size I hope to be adjusted

### ISSUE THREAD

**Issue by fuzheng1998** [mbadolato/iTerm2-Color-Schemes#179]
the windows size of themes is too slim && font is too small to see, so I recommend myselves' 
font : Menlo 15
windows: 80*24
if seeking reference, look at [this](https://github.com/nicolashery/mac-dev-setup#beautiful-terminal)

**Comment by mbadolato** [comment]
@fuzheng1998 I'm not sure what you're referring to. The themes only dictate color schemes. You're required to set your own font faces and sizes in your profiles
