### ISSUE TITLE
Can't change color in Mac Os Mojave

### ISSUE THREAD

**Issue by miluki01** [mbadolato/iTerm2-Color-Schemes#182]
Hi, I tried to import a dozen colour schemes but they do not work at all.

**Comment by miluki01** [comment]
<img width="978" alt="Screenshot 2019-04-05 at 22 09 54" src="https://user-images.githubusercontent.com/9244654/55637659-c37c1500-57ef-11e9-9c6c-a0d14a419c41.png">
<img width="549" alt="Screenshot 2019-04-05 at 22 11 55" src="https://user-images.githubusercontent.com/9244654/55637705-e4dd0100-57ef-11e9-9916-38daa66f8d70.png">
You can see, it still white!

**Comment by LYJSPEEDX** [comment]
Hi! @miluki01 
Can U give my your app version?
I installed V4.0.1 and meet the same problem, while my interface is quite different from you.
I wonder whether the latest version causes the problem.

**Comment by miluki01** [comment]
Hi @LYJSPEEDX  
It is 3.2.8. I got it from brew. I also tried the version from the official website but it got the same problem.

**Comment by mbadolato** [comment]
Version 4.0.1 and 3.2.8 of what?

I'm on Mojave and color schemes are working just fine. From the screenshot above I cannot tell what the issue is it looks like you're colors on the screen are exactly what they should be for the selected theme based on the color blocks in the ANSI section

**Comment by ravi-oli** [comment]
@miluki01 Are you facing issue with Color Presets which are shipped with iTerm2? or only with custom Presets? 

For instance, from screenshot you've shared - does Tango Dark / Tango Light works? If yes, then it must ben an issue with Custom Presets files format (probably the way it has been saved). 

I had faced similar challenge before, wherein I saved a Preset file manually, imported it and it didn't work (I think I messed with extension). I had cloned the Presets repository and then imported and it worked just fine.

**Comment by VishalNehra** [comment]
I'm also facing this issue. Tango themes aren't working either. They just change the background, no change in color. 
Unrelated to this issue - I'm new to this software, could you also tell me how can I choose from different columns in screenshot of each theme.

**Comment by gloryVine** [comment]
Same issue. Only the background color changes.

**Comment by nolongerwait** [comment]
Same issue. Only the background color changes. +1

**Comment by meow232309** [comment]
same issue for me.

**Comment by mbadolato** [comment]
These issues don't have anything to do with the themes themselves. It's something with your terminals' setup (terminal type, output, something with the shell). 

I'm not able to help diagnose unfortunately

**Comment by nolongerwait** [comment]
> These issues don't have anything to do with the themes themselves. It's something with your terminals' setup (terminal type, output, something with the shell).
> 
> I'm not able to help diagnose unfortunately

But in its README, it says that we just run it can change the color. Unfortunately it does work, and we did not change anything in settings.

**Comment by mbadolato** [comment]
And normally that's the case. If there's something off (something with the shell, a terminal type setting, CLICOLOR (which probably should not be equal to 1 as in the screenshot posted earlier in the thread), that's something local. These themes are just values that the terminal program(s) use; there's nothing specific to the themes to do. If it's not working on a machine, it's something with that machine's setup, not the theme files

**Comment by nolongerwait** [comment]
This machine is a brand new machine, no one has changed the settings of the terminal and machine, and no terminal program is installed.  So why the theme do not work?  If the theme file requires some settings to be set in advance, why is it not mentioned in the README file?

Also, thank you for some suggestions, I will try it out after getting up tomorrow.

**Comment by meow232309** [comment]
same brand new - no one messed with it .
