### ISSUE TITLE
Solarized palette is inaccurate

### ISSUE THREAD

**Issue by antoineco** [mbadolato/iTerm2-Color-Schemes#193]
All Solarized themes seem to be generated from [xrdb/Solarized Dark.xrbd](https://github.com/mbadolato/iTerm2-Color-Schemes/blob/20900a9b58012b22fd65abe90fe86b2899e6de6d/xrdb/Solarized%20Dark.xrdb), but the colors defined in this file are nowhere to be be found in the Solarized [values reference](https://github.com/altercation/solarized#the-values) (regardless of the issue discussed in #62/#63). This is "close enough", but inaccurate. Was this a conscious decision?

Comparison:

| term color | reference | this repo |
|------------|-----------|-----------|
| 0          | `#073642` | `#002831` |
| 1          | `#dc322f` | `#d11c24` |
| 2          | `#859900` | `#738a05` |
| 3          | `#b58900` | `#a57706` |
| 4          | `#268bd2` | `#2176c7` |
| 5          | `#d33682` | `#c61c6f` |
| 6          | `#2aa198` | `#259286` |
| 7          | `#eee8d5` | `#eae3cb` |

**Comment by mbadolato** [comment]
No. It's possible adjustments were made and submitted over the years but I don't know. If you'd like to submit an update to the iTerm color schemes file and submit it, we can then run the translator on it and regenerate all of the other formats

**Comment by antoineco** [comment]
Ah iTerm themes are canonical, got it. :+1: Let me put on my TODO list.

**Comment by mbadolato** [comment]
Much appreciated!
