### ISSUE TITLE
Question

### ISSUE THREAD

**Issue by TerensTare** [mbadolato/iTerm2-Color-Schemes#197]
Does any of these themes suport PowerLine?

**Comment by mbadolato** [comment]
Sure, the themes are just color schemes so whatever you do within the shell is fine. I'm using Powerlevel9k in my shell (zsh) which is very powerline-like. I've also use the powerline with Vim plugins before. looks good!

![Screen Shot 2019-07-03 at 4 44 34 PM](https://user-images.githubusercontent.com/164615/60630996-e3e94a80-9db1-11e9-9227-f92c08b01d41.png)
