### ISSUE TITLE
Duplicate "Paraiso Dark" and "Parasio Dark" themes

### ISSUE THREAD

**Issue by rakuco** [mbadolato/iTerm2-Color-Schemes#198]
The "Paraiso Dark" theme seems to have been originally added in commit fd97e4b9e4c8edd7fb47f6a02e30c366688c73c0, and its name ended up with a typo ("Parasio" rather than "Paraiso").

In practice, this means there are duplicate "Paraiso Dark" and "Parasio Dark" themes in many of the subdirectories in the tree.

**Comment by mbadolato** [comment]
Ah cool, good to know. I'll check it out when i'm home from vacation :) Thanks!

**Comment by mbadolato** [comment]
Sorry, haven't had a chance to look at this yet. Any chance you could submit a PR to fix the issue?

**Comment by jdhmtl** [comment]
Looks like this may have been resolved in #211

**Comment by rakuco** [comment]
> Looks like this may have been resolved in #211

Only partially. I'm fixing the rest in #299.
