### ISSUE TITLE
Solarized dark theme doesn't work in iTerm2 Build 3.2.9

### ISSUE THREAD

**Issue by binbjz** [mbadolato/iTerm2-Color-Schemes#200]
iTerm2 in version 3.2.9 doesn't accept color preset when importing Solarized dark theme. The other theme works well.

# It works well if I used built-in ls.
<img width="283" alt="Screen Shot 2019-07-22 at 22 42 32" src="https://user-images.githubusercontent.com/8213913/61641637-08aa5100-acd2-11e9-9206-257e9ef791f3.png">

# Hardware Overview:
  Model Name:	MacBook Pro
  Model Identifier:	MacBookPro15,3
  Processor Name:	Intel Core i9
  Processor Speed:	2.4 GHz
  Number of Processors:	1
  Total Number of Cores:	8
  L2 Cache (per Core):	256 KB
  L3 Cache:	16 MB
  Hyper-Threading Technology:	Enabled
  Memory:	32 GB

# I have installed coreutils and added a "gnubin" directory to my PATH from my bashrc
$ brew info coreutils
coreutils: stable 8.31 (bottled), HEAD

# Use these commands with their normal names
PATH="/usr/local/opt/coreutils/libexec/gnubin:$PATH"
MANPATH="/usr/local/opt/coreutils/libexec/gnuman:$MANPATH"
export PATH
export MANPATH

# Used the coreutils's ls
$ which ls
/usr/local/opt/coreutils/libexec/gnubin/ls

$ alias la
alias la='ls --color -la'

<img width="535" alt="Screen Shot 2019-07-22 at 22 29 44" src="https://user-images.githubusercontent.com/8213913/61640775-81101280-acd0-11e9-9c13-29b308553e06.png">

<img width="980" alt="Screen Shot 2019-07-22 at 23 00 18" src="https://user-images.githubusercontent.com/8213913/61643023-9b4bef80-acd4-11e9-95b6-8cd5ee96eac3.png">

**Comment by mbadolato** [comment]
That's not an issue with the themes. It's likely something with your setup and the coreutils ls. Make sure you are using color output. Also try some of the tips in this thread: https://github.com/mbadolato/iTerm2-Color-Schemes/issues/81

**Comment by binbjz** [comment]
> That's not an issue with the themes. It's likely something with your setup and the coreutils ls. Make sure you are using color output. Also try some of the tips in this thread: #81

The others color themes work well. Only solarized doesn't work

**Comment by mbadolato** [comment]
I don't know what to tell you. It has to be something with corels or with the local setup. If you find an answer, I'd be curious to know, but I've never heard of an issue with all themes but one working

**Comment by mbadolato** [comment]
Also, could very well be that corels is using the `Bright` colors and if you look at those in your screenshot, they're mostly pretty similar to each other. Maybe just not enough for the eye to be discerning?
