### ISSUE TITLE
I can't import Color scheme

### ISSUE THREAD

**Issue by SirPhemmiey** [mbadolato/iTerm2-Color-Schemes#210]
I am currently on a macOS Mohave and iTerm version 2.9.5.

There's no place to import colour schemes. I've battled with it for a while now and I can't seem to find it is. 

Please help, thanks.

**Comment by mbadolato** [comment]
<img width="1040" alt="Screen_Shot_2019-10-21_at_8_49_12_PM" src="https://user-images.githubusercontent.com/164615/67258259-8eaa7500-f444-11e9-821c-4f1836464f1d.png">

Go there, scroll to the bottom, choose Import! 😃

**Comment by SirPhemmiey** [comment]
Hey man, see what i can find here

<img width="658" alt="Screen Shot 2019-10-22 at 9 14 46 AM" src="https://user-images.githubusercontent.com/22390818/67268457-6f473280-f4ac-11e9-8a7a-a1414eef76c8.png">

**Comment by mbadolato** [comment]
1) That's Terminal, not iTerm
2) Click the gear icon, bottom left, right next to `Default`

😄

**Comment by SirPhemmiey** [comment]
My bad, thanks!
