### ISSUE TITLE
Adding coffee theme

### ISSUE THREAD

**Issue by cbitterfield** [mbadolato/iTerm2-Color-Schemes#217]
How to I get a pull request done.
I have created a new them on a branch locally but I can't push it up for a pull request.

New to GIT so a little help would be useful

I cloned the repository, added a branch locally. Created the theme. I created the screen shoy and ran the tools I have a committed branch locally and want to get a pull request on this.

**Comment by mbadolato** [comment]
I see you got it figured out with the PR you submitted. I'll close this
