### ISSUE TITLE
"Remina" in title should be "Remmina".

### ISSUE THREAD

**Issue by comradekingu** [mbadolato/iTerm2-Color-Schemes#219]
Over 200 terminal color schemes/themes for iTerm/iTerm2. Includes ports to Terminal, Konsole, PuTTY, Xresources, XRDB, **Remina** …
Should be "Remmina", (as per https://remmina.org/) and maybe it would be best to have "Includes ports to" in the README.

**Comment by mbadolato** [comment]
Thanks and great suggestion! I thought I did that long ago but apparently not. Updated!
