### ISSUE TITLE
cursorColor and selectionBackground missing in Windows Terminal settings

### ISSUE THREAD

**Issue by stillhart** [mbadolato/iTerm2-Color-Schemes#240]
The Windows Terminal configs in the  `windowsterminal` folder seem to lack the following keys:
```json
{
  "cursorColor": "#fc0000",
  "selectionBackground": "#c9c9c9",
}
```
See [Microsoft Windows Terminal Color Scheme Documentation](https://docs.microsoft.com/de-ch/windows/terminal/customize-settings/color-schemes)

I noticed this when using white backgrounds.

**Comment by jdhmtl** [comment]
I think this was fixed in #280
