### ISSUE TITLE
Peppermint Color Scheme

### ISSUE THREAD

**Issue by isacsandin** [mbadolato/iTerm2-Color-Schemes#242]
Hi!, there is an awesome theme for mac users called Peppermint, first released [here](https://noahfrederick.com/log/lion-terminal-theme-peppermint)

There is a port for iTerm2 developed for dotzero in this [link](https://github.com/dotzero/iTerm-2-Peppermint)

Can you please make a port to Windows Terminal ? 

I'm posting the links instead of making a pull request to give the credits to the creators.

Thanks!

**Comment by mbadolato** [comment]
Hi, please submit a pull request. You can give credit to the author via the README file. The iterm2 port would need to be added, then there's a conversion script in the tools directory that will port to the other formats, including the windows terminal.  Thanks!
