### ISSUE TITLE
options distinguish git diff changes in Batman theme

### ISSUE THREAD

**Issue by danedavid** [mbadolato/iTerm2-Color-Schemes#258]
Hi, I'm using the Batman color preset with iTerm2 + zsh, and the diff color for git is the same for deletion & insertion:
![image](https://user-images.githubusercontent.com/19928280/94550755-e6b34380-0271-11eb-8467-84eff7637e6f.png)

This makes it kind of difficult to read the diff. Is there any way these colors can be customized?

**Comment by tehaleph** [comment]
Yellow for "red" and "green" in this theme looks like the main idea.

My suggestion is to customize colors in git. To do this, you can use the following command (or write into .gitconfig). You can use any hex or ANSI 256 color values:

`git config --global color.diff.new "#FFC0EB"`

Before:
![CleanShot 2020-09-29 at 18 39 05](https://user-images.githubusercontent.com/13217394/94581080-53830980-0283-11eb-84ad-b73120051fff.png)
After:
![CleanShot 2020-09-29 at 18 40 27](https://user-images.githubusercontent.com/13217394/94581097-57169080-0283-11eb-887f-a24a707e8874.png)

You'll need to change the following settings:
color.diff.old - color of removed lines
color.diff.new - color of added lines

Hope this helps!

**Comment by danedavid** [comment]
Worked! Thanks a bunch! Shouldn't have created this issue!

**Comment by mbadolato** [comment]
Also take a look at [diff-so-fancy](https://github.com/so-fancy/diff-so-fancy) I have my git configured to use it by default, and it allows you to customize the colors as well as being a better to read format

From my `~/.gitconfig`:

in the `[core]` section: 
```pager = `brew --prefix git`/share/git-core/contrib/diff-highlight/diff-highlight | less```

in the `[pager]` esction: 
```
  show = diff-so-fancy | less --tabs=4 -RFX
  diff = diff-so-fancy | less --tabs=4 -RFX
```
