### ISSUE TITLE
Running import scheme scripts throws an error

### ISSUE THREAD

**Issue by jav-12** [mbadolato/iTerm2-Color-Schemes#268]
I downloaded the repo and tried to follow the wiki to install all schemes:

```
❯ ./import-scheme.sh -v ../schemes/*
./import-scheme.sh: line 187: unexpected EOF while looking for matching `''
./import-scheme.sh: line 191: syntax error: unexpected end of file
```

I got a syntax error

**Comment by mbadolato** [comment]
Interesting. What system are you on? I just ran it and it worked fine. Note, I have never used this script before (it was a contribution), but it worked just fine. MacOS running ZSH

<img width="773" alt="Screen Shot 2021-01-23 at 1 21 38 PM" src="https://user-images.githubusercontent.com/164615/105613152-11c02680-5d7e-11eb-83bf-fe5cc963bbdc.png">

**Comment by HoYoung1** [comment]
Same issue, it doesn't work.  (MacOS running ZSH)

![image](https://user-images.githubusercontent.com/35159888/105621512-81501780-5e4b-11eb-8520-f37170e31a0e.png)

**Comment by jav-12** [comment]
> Interesting. What system are you on? I just ran it and it worked fine. Note, I have never used this script before (it was a contribution), but it worked just fine. MacOS running ZSH
> 
> <img alt="Screen Shot 2021-01-23 at 1 21 38 PM" width="773" src="https://user-images.githubusercontent.com/164615/105613152-11c02680-5d7e-11eb-83bf-fe5cc963bbdc.png">
> 
> And with the `-v` option:
> <img alt="Screen Shot 2021-01-23 at 1 23 46 PM" width="801" src="https://user-images.githubusercontent.com/164615/105613175-48963c80-5d7e-11eb-877f-2c6c05c58e37.png">


MacOs BigSur running Zsh with oh-my-zsh

**Comment by colintsteele** [comment]
![image](https://user-images.githubusercontent.com/12700471/106061266-2cb6d180-60c3-11eb-95d7-cffa9cced73a.png)
Same issue. MacOS Big Sur on ZSH

**Comment by mbadolato** [comment]
@XuehaiPan This was the script you submitted. Any thoughts?

**Comment by XuehaiPan** [comment]
The old version of `Bash` might not support `heredocs` well. I will fix it right away.

**Comment by mbadolato** [comment]
@XuehaiPan Thanks for jumping on that so quickly

@HoYoung1 and @colintsteele Does this fix for you?

**Comment by HoYoung1** [comment]
@mbadolato @XuehaiPan 
Thanks, It works well.
