### ISSUE TITLE
https://github.com/mbadolato/iTerm2-Color-Schemes/blob/master/xrdb/Slate.xrdb

### ISSUE THREAD

**Issue by pandada8** [mbadolato/iTerm2-Color-Schemes#30]
this file is filled with wrong content by mistake

**Comment by mbadolato** [comment]
In what regards? I just loaded the file from the repo and the colors look like the screenshot

**Comment by pandada8** [comment]
well i get this in the content

	On branch slate
	Untracked files:
	  (use "git add <file>..." to include in what will be committed)

		screenshots/slate.png
		slate.txt

	nothing added to commit but untracked files present (use "git add" to track)

i suppose that some wrong redirection happened while converting the colorscheme into the xrdb format :(

**Comment by mbadolato** [comment]
Ahhh, sorry... Totally missed the fact that you specifically specified the xrdb file. This is what happens when I don't yet have my coffee. I was looking at the actual scheme file.  

The xrdb file was one that was submitted to me (IIRC). I'll look into updating it. 

Thanks!
