### ISSUE TITLE
iterm2terminal.swift script issue

### ISSUE THREAD

**Issue by pratikmullick** [mbadolato/iTerm2-Color-Schemes#305]
```
./iterm2terminal.swift:106:45: warning: 'archivedData(withRootObject:)' was deprecated in macOS 10.14: Use +archivedDataWithRootObject:requiringSecureCoding:error: instead
            let colorData = NSKeyedArchiver.archivedData(withRootObject: color)
                                            ^
./iterm2terminal.swift:118:28: warning: 'archivedData(withRootObject:)' was deprecated in macOS 10.14: Use +archivedDataWithRootObject:requiringSecureCoding:error: instead
    return NSKeyedArchiver.archivedData(withRootObject: font)
                           ^
unable to load ./iterm2terminal.swift
converting ../schemes/HaX0R_R3D.itermcolors -> ../schemes/HaX0R_R3D.terminal
```

When trying to use the `iterm2terminal.swift` script in macOS BigSur, the aforementioned error message is popping up.

**Comment by mbadolato** [comment]
Hmmm.

I don't speak much Swift so won't be able to debug that one. I'll have to see if I can find the original author in the closed PRs and ping them perhaps

**Comment by jdhmtl** [comment]
What do you think about converting this to Python, @mbadolato? Keep all the tools in one language as much as possible. Happy to take a stab at that conversion.

**Comment by mbadolato** [comment]
That works for me. I've thought about moving to a different language altogether since I don't speak much python, but I have no time/inclination for that now anyway. Having them in one consistent language (regardless of which one) is beneficial

**Comment by pratikmullick** [comment]
@jdhmtl I can also pitch in with Python conversion. Let me take a deeper look at the script.

**Comment by pratikmullick** [comment]
Please move forward. I am unable to convert the XML structure into something that I can use in Python (Python dict structure preferably).
