### ISSUE TITLE
You said to ping

### ISSUE THREAD

**Issue by Couto** [mbadolato/iTerm2-Color-Schemes#31]
Since you said to ping...

The Spacedust theme was originally ported by me to iTerm, and the original theme was done by @mhallendal who deserves all the credits.

You can find the repository here: https://github.com/mhallendal/spacedust-theme

**Comment by mbadolato** [comment]
@Couto Does the scheme need to be updated/replaced or just the credits adjusted?

**Comment by Couto** [comment]
I was referring to the note on the website, so I meant the credits.

However I tried the one on your repository and the colors don't match at all the screenshot provided (at least on my iterm) so it might also need an update, but I'll leave that up to you :)

Anyway heres a screenshot of how the spacedust theme on your repository looks like: 

![https://cldup.com/y37VC372hu.png]()

(oh boy I come to report one thing, and now I'm reporting another... sorry)

**Comment by mbadolato** [comment]
Wow good catch on the definition file. not sure what happened there! Fixed, and adjusted the credits. Thanks!
