### ISSUE TITLE
License

### ISSUE THREAD

**Issue by varemenos** [mbadolato/iTerm2-Color-Schemes#32]
Under what license is this repository distributed?

**Comment by mbadolato** [comment]
There really isn't a license associated as most of the themes are ones that I've found on the net, available for free but no specific licenses attached, and collected. Some I've made. 

So, I suppose I could stick a CC license or MIT or whatever on it but since this is more of a collected work then a created work, it didn't really make sense. I suppose I could put something on there and indicate that each theme is owned by its creator and the collection itself is license blah blah blah.  I'll think about something along those lines.

**Comment by varemenos** [comment]
Alright that answers my question, thanks.
Feel free to either close the issue or use it as a reminder to write that indication

**Comment by kevin-smets** [comment]
If you provide no license, isn't it copyrighted by default? See http://blog.codinghorror.com/pick-a-license-any-license/

Quote from the article:

> Because I did not explicitly indicate a license, I declared an implicit copyright without explaining how others could use my code. Since the code is unlicensed, I could theoretically assert copyright at any time and demand that people stop using my code.

**Comment by mbadolato** [comment]
@kevin-smets This is just a collection not a copyrighted work. Schemes created by others and included here are not mine to assign my own copyright to. I get what you're saying but I don't think it applies here, nor do I want the hassle of trying to curate licenses for individual schemes etc. This is a resource I started keeping just so I had themes in one place. Others find it useful and are welcome to use it, but it's not my own copyrighted work (unless you consider the collection copyrightable, which I don't)

**Comment by aloisdg** [comment]
>  (unless you consider the collection copyrightable, which I don't)

Awesome lists use the CC0 license.

**Comment by mbadolato** [comment]
Again though, I don't own the copyrights on the included schemes so am hesitant to assign my own copyright to the repo

**Comment by aloisdg** [comment]
@mbadolato as you want. but without a license we are not allowed to use it.

**Comment by mbadolato** [comment]
I disagree, but if it would make people happy I can stick something on there saying the collection as collected by me is free to use but individual schemes are copyright by their respective owners

**Comment by aloisdg** [comment]
> Without a license, the code is copyrighted by default. People can read the code, but they have no legal right to use it. To use the code, you must contact the author directly and ask permission.


> the collection as collected by me is free to use but individual schemes are copyright by their respective owners

I am not a lawyer but it should do the job I guess.

**Comment by mbadolato** [comment]
Added MIT for the collection itself. each theme's license and copyright are per the theme's creator
