### ISSUE TITLE
Feature: DOS Color Scheme

### ISSUE THREAD

**Issue by tracker1** [mbadolato/iTerm2-Color-Schemes#331]
Would be nice to have a color scheme that matches the classic DOS default color scheme including proper brown.

https://en.wikipedia.org/wiki/Color_Graphics_Adapter

**Comment by mbadolato** [comment]
If you'd like to submit it in .itermcolors format, I'd be happy to include it!

**Comment by tracker1** [comment]
@mbadolato will look into it if @jdhmtl doesn't get it first... I'm not really familiar with the .itermcolors format.

@jdhmtl yes, that looks about right...

**Comment by jdhmtl** [comment]
I’ve got that saved in a branch in my fork. Wanted to make sure this was what you were looking for before moving forward. All that’s left really is to run the update script to create the other formats. Should be able to have this ready tomorrow.
