### ISSUE TITLE
Pull Request Templates?

### ISSUE THREAD

**Issue by jdhmtl** [mbadolato/iTerm2-Color-Schemes#340]
Is there value in creating a [pull request template](https://docs.github.com/en/communities/using-templates-to-encourage-useful-issues-and-pull-requests/creating-a-pull-request-template-for-your-repository) to provide users a checklist of things required for submitting -- run `update_all.py`, include screenshot, update credits, etc -- which may not be immediately obvious?

**Comment by mbadolato** [comment]
Sure!
