### ISSUE TITLE
How to change the font color in the title of iTerm 2?

### ISSUE THREAD

**Issue by imchriscaro** [mbadolato/iTerm2-Color-Schemes#355]
<img width="1264" alt="QKy5i" src="https://user-images.githubusercontent.com/74562554/153799315-c82d9865-6d08-47aa-92f4-306813f61eb0.png">
Does anyone know how to change the font color in the title of iTerm 2 from grey to white? I've been trying to make this change for more than a week but was unsuccessful in all of my efforts. I suspect that exporting your profile as a .json might help, but whenever I was making direct changes to the file, nothing was really changing. I should add that I'm not familiar with .json, so perhaps this is the reason why I couldn't tweak it the way I want. I need your help, guys! 😇

**Comment by mbadolato** [comment]
That isn't part of the theming, that's part of the iterm application itself. I suspect that is not configurable but it's possible it's available somewhere in the application's settings area
