### ISSUE TITLE
xrdb/Batman.xrdb broken

### ISSUE THREAD

**Issue by loreb** [mbadolato/iTerm2-Color-Schemes#37]
I guess there's something wrong with tools/iterm2xrdb, but I don't speak ruby :)

Batman.xrdb has lines like
#define 1 #00ed6c
#define 1 #007174
#define 0_5 #00f789
which are completely nonsensical
$ ./tools/iterm2xrdb < schemes/Batman.itermcolors | cmp - xrdb/Batman.xrdb
says that Batman.xrdb is exactly the output of the conversion, so, assuming the the iterm theme is ok (I don't have a mac), well, good luck (and thank you for all the colors btw!)

edit: same goes for hulk&spiderman

**Comment by mbadolato** [comment]
Yeah sometimes the translation script doesn't work if there are missing (optional) values in the original itermcolors files. I've never fully looked into it (I didn't write the script). Thanks for letting me know; I'll look into it when I have some time

**Comment by sunaku** [comment]
That happens because the Batman.itermcolors file is specifying an extra `Color Space` key whereas all other colorschemes don't.  Remove those extra keys and the conversion should work properly. :hammer:

**Comment by sunaku** [comment]
Pull request #38 submitted to fix this issue. :rocket:

**Comment by mbadolato** [comment]
Thanks @sunaku!

**Comment by sunaku** [comment]
Glad to help! :santa: We can close this issue now. :runner:
