### ISSUE TITLE
Question: How is the website generated?

### ISSUE THREAD

**Issue by sayeefm0** [mbadolato/iTerm2-Color-Schemes#376]
I recently added a theme (`Wilmersdorf`) and noticed that the https://iterm2colorschemes.com website is not automatically updated. Ideally this repo would have an actions workflow to update the website on push - can someone point me to how the website is generated so I can try my hand at that?

Thanks!

**Comment by mbadolato** [comment]
That's not an auto-generated size and TBH I've forgotten about generating it for quite some time

There's a genHTML script in the /tools directory that can generate the blocks, which then need to replace the current HTML blocks.  The website's data is in index.html, on the `gh-pages` branch (That branch is specifically for the site, and has files different than the main branch)

**Comment by mbadolato** [comment]
I just pushed an update; it should show soon
