### ISSUE TITLE
是否支持密钥转发设置，如何设置呢

### ISSUE THREAD

**Issue by yidoa** [mbadolato/iTerm2-Color-Schemes#385]

**Comment by mbadolato** [comment]
From Google Translate:

> Does it support key forwarding settings? How to set it?

I'm not sure what that means?

**Comment by mbadolato** [comment]
@halfelf Thanks for the confirmation. I know Translate can be really wonky so when it came back that meaningless that I couldn't surmise, I just thought it did a bad job
