### ISSUE TITLE
New Theme - Apple Classic

### ISSUE THREAD

**Issue by CodeMonkeyBrian** [mbadolato/iTerm2-Color-Schemes#394]
I want to submit a new theme that mimics the classic Apple II amber color. Not sure how to do that so I'm attaching it here.
[Classic Apple Dark Amber.itermcolors.zip](https://github.com/mbadolato/iTerm2-Color-Schemes/files/9617302/Classic.Apple.Dark.Amber.itermcolors.zip)

**Comment by prateektade** [comment]
Hi @CodeMonkeyBrian! Would it be ok if I create a pull request to add this theme?

**Comment by mbadolato** [comment]
Got it, thank you both
