### ISSUE TITLE
Putty colors question

### ISSUE THREAD

**Issue by clach04** [mbadolato/iTerm2-Color-Schemes#422]
I imported Dracula and Dracula+ into Putty (0.78) under Microsoft Windows 10 and the colors I have appear brighter than the screen shots for:

* https://github.com/mbadolato/iTerm2-Color-Schemes#dracula
      * https://github.com/mbadolato/iTerm2-Color-Schemes/blob/master/screenshots/dracula.png
* https://github.com/mbadolato/iTerm2-Color-Schemes#dracula-1
      * https://github.com/mbadolato/iTerm2-Color-Schemes/blob/master/screenshots/Dracula+.png

## My Screen shots

using https://github.com/clach04/terminal_style_toolkit/blob/main/show_colors.bash

### iterm2 Dracula putty

![image](https://github.com/mbadolato/iTerm2-Color-Schemes/assets/424032/a943291a-5f6f-4293-b8f0-d5355962c4b8)

### iterm2 Dracula+ putty

![image](https://github.com/mbadolato/iTerm2-Color-Schemes/assets/424032/debc1d54-f77d-49ec-ba19-c7b7caaf8353)

Is this likely due to a difference in Window and Mac? I'm assuming the screenshots are from an iterm2? I do not have access to a Mac to determine this myself.

Not a major issue but I'd like to understand why I'm seeing something different

**Comment by mbadolato** [comment]
It could be a WIndows vs Mac thing. It could also be just terminal handling of colors on your platform. I'm not really sure.
