### ISSUE TITLE
Material and MaterialDark

### ISSUE THREAD

**Issue by robwise** [mbadolato/iTerm2-Color-Schemes#43]
Material and MaterialDark both can be imported and loaded without error, but don't actually change colors (this is in iTerm2). All other schemes from the repo that I've tried work with no issue. Can you confirm if there is indeed a problem with these two themes?

**Comment by mbadolato** [comment]
Hmmm, they're both working just fine for me.  I already had Dark in my list and it switched over just fine. I imported the Material (light) scheme and it worked as well.  Which version of iTerm are you using (Latest, the beta, the nightly)? I'm using nightlies here

**Comment by robwise** [comment]
@mbadolato Yep, that was it! I was using 2.1.1, which is the latest stable build, but I installed the nightly build and it both Material and MaterialDark work all of the sudden!

**Comment by mbadolato** [comment]
Interesting!

@gnachman Any thoughts on why that could be the case? Do newer version of iTerm have different settings in the ```.itermcolors``` files?

**Comment by gnachman** [comment]
2.9 adds a new field for colorspace but 2.1 ought to ignore it. I'll try to reproduce the issue.

**Comment by gnachman** [comment]
It looks like the issue is that after you've used 2.9.x (nightly build or latest beta), your profile will have an entry for "Link Color". 2.1 gets angry that your color preset is missing an entry for it. The easiest solution is to re-export the arrangement with 2.9 and reload it.

**Comment by mbadolato** [comment]
Good to know, thanks!
