### ISSUE TITLE
Add Four Selenized Schemes for MobaXterm Terminal

### ISSUE THREAD

**Issue by aalekseenkov** [mbadolato/iTerm2-Color-Schemes#432]
I created four themes based on [Selenized](https://github.com/jan-warchol/selenized) for my MobaXterm and would like to add them into [directory](https://github.com/mbadolato/iTerm2-Color-Schemes/tree/master/mobaxterm) of this repository:  
- selenized-black.ini
- selenized-dark.ini
- selenized-light.ini
- selenized-white.ini  

Where can I find CONTRIBUTE.md or any instructions to help you?

**Comment by mbadolato** [comment]
https://github.com/mbadolato/iTerm2-Color-Schemes?tab=readme-ov-file#contribute

**Comment by aalekseenkov** [comment]
I have generated a lot of new files according your manual about adding new themes from [the original selenized iTerm files](https://github.com/jan-warchol/selenized/tree/master/terminals/iterm) and now I am a little bit confused. We got schemes with AppleRGB colors for all terminals but Linux apps should have sRGB colors. 
```
Color        CIE L*a*b*   HSB           sRGB      AppleRGB
----------   ----------   -----------   -------   --------
bg_0         23 -12 -12   193  77  28   #103c48   #112e38
bg_1         28 -13 -13   193  72  34   #184956   #163945
bg_2         36 -13 -13   194  57  41   #2d5b69   #254a57
dim_0        56  -8  -6   191  20  56   #72898f   #61777c
fg_0         75  -5  -2   182   8  74   #adbcbc   #9faeae
fg_1         85  -5  -2   182   7  85   #cad8d9   #bfd0d0

red          60  63  40     2  68  98   #fa5750   #f13c3e
green        69 -38  55    92  70  73   #75b938   #69ad21
yellow       75   6  68    46  79  86   #dbb32d   #d1a416
blue         60   0 -57   213  72  97   #4695f7   #3a82f8
magenta      66  55 -15   325  52  95   #f275be   #e75bb3
cyan         73 -40  -4   174  67  78   #41c7b9   #42bdaa
orange       67  37  50    22  69  93   #ed8649   #e26f35
violet       64  30 -45   263  42  92   #af88eb   #9b72e9

br_red       66  63  40     3  65 100   #ff665c   #ff4b49
br_green     74 -38  55    92  65  78   #84c747   #78be2e
br_yellow    80   6  68    46  74  92   #ebc13d   #e4b424
br_blue      66   0 -57   214  66 100   #58a3ff   #4a91ff
br_magenta   72  55 -15   325  49 100   #ff84cd   #fb69c4
br_cyan      78 -40  -4   173  61  84   #53d6c7   #50cfba
br_orange    72  37  50    22  66  99   #fd9456   #f67e41
br_violet    69  30 -45   263  40  98   #bd96fa   #ab80fc
```
To avoid this I could create eight selenized themes like selenized-dark-AppleRGB, selenized-dark-sRGB and etc. But it will mess people so I think that I should close this task at all. What is your opinion?

**Comment by mbadolato** [comment]
Hmmm. I would prefer not to create eight additional themes. Is there something wrong with one of the converters causing the wrong values to be used? The converters are in the tools directory. Unfortunately, I'm not too familiar with how they work as I didn't create them

**Comment by aalekseenkov** [comment]
Your converters are awesome! But for example we input AppleRGB #112e38 for background and get all schemes with this color but for Linux apps we should use #103c48. I could copy manually files for different kinds of terminals but it will break all your repo's idea. I do not want to create a lot of themes with the same name too and will ask you to close this issue.
