### ISSUE TITLE
Source of colors?

### ISSUE THREAD

**Issue by jondot** [mbadolato/iTerm2-Color-Schemes#46]
Hi,
I find the themes extremely good, that I want to take them to XCode and macvim. From looking around, I don't think there's an easy mapping.
Can you shed some more light about how the colors were picked? did you use a source baseline themes (from vim, or such)?. Hopefully I can trace back and use those in my editors as well :)

Thanks

**Comment by jondot** [comment]
Ah, found it on the README. Headslap :+1:

**Comment by mbadolato** [comment]
Heh yeah that bad-boy's hidden right in the main folder :wink: :)  If you have any other themes you'd like to contribute, please send in via PR!

Cheers!

**Comment by jondot** [comment]
Looks like a perfect collection. I only wish I somehow magically had all these schemes in Vim. I must say the higher contrast solarized looks like what solarized should have been!

**Comment by mbadolato** [comment]
Yeah I really like that one too. Solorized is pretty popular but it's never really done it for me. I like the HC version a lot though. My default go-to is Symfonic, but I also really like Argonot and a few others. I tend to assign different schemes for different profiles (like red background ones for production machines etc) so it's nice having a variety available

**Comment by jondot** [comment]
Will definitely check Symfonic. I'm happy to meet other people with the same obsession for color schemes like mine :)
I decided to curate the sources and variations for schemes in a list: http://github.com/jondot/awesome-colorschemes.
I've been doing the OCDish research every few years when I feel like swapping colors, and the challenge is matching the same theme to my various editors (Xcode, IDEA, Vim, terminal). 
Today I mostly use ir_black and a sublime-text knockoff scheme. I used to be a Monokai/Molokai and VibrantInk fan :)

**Comment by mbadolato** [comment]
Haha nice! Yeah I like to make everything match too. This repo started out because I couldn't find any good themes for iTerm so started collecting them. Now there's 100-ish and a few people have submitted ports for Terminal, xrdb, Terminator etc.  One of these years I'm going to put up a new version of the site (that's like 1/2 done) that allws for voting, ranking, easily submitting, etc

**Comment by jondot** [comment]
Excellent work! :+1:
