### ISSUE TITLE
Material Colour Schemes doesn't work.

### ISSUE THREAD

**Issue by mazedulislamkhan** [mbadolato/iTerm2-Color-Schemes#47]
Material colour scheme and the dark version both doesn't work.

**Comment by mbadolato** [comment]
Someone else had this issue recently and it seemed to be related to the iTerm version. See [here](https://github.com/mbadolato/iTerm2-Color-Schemes/issues/43) for details. Can you let me know if that's your issue as well?

**Comment by mazedulislamkhan** [comment]
You're absolutely correct. I'm having the exact same issue.

**Comment by mbadolato** [comment]
Did the solution in that thread (newer version of iTerm) fix your issue?

**Comment by mazedulislamkhan** [comment]
No, It didn't fix my issue as I never installed nightly build or beta version of iTerm. So, I'm not using Oceanic Material theme and it works correctly as expected.

**Comment by mbadolato** [comment]
Ah. Well, should be fixed then when iTerm has it's next stable release. Cheers!
