### ISSUE TITLE
Add missing Tokyonight scheme: Moon

### ISSUE THREAD

**Issue by alosarjos** [mbadolato/iTerm2-Color-Schemes#478]
Since all 3 out of 4 schemes al added, I would like to see if the fourth one can be added.

I don't have MacOS/iTerm to follow the contributing instructions

URL of the Theme: https://github.com/folke/tokyonight.nvim

**Comment by akx** [comment]
This was resolved by https://github.com/mbadolato/iTerm2-Color-Schemes/pull/480, I think.
