### ISSUE TITLE
Explanation of screenshots

### ISSUE THREAD

**Issue by varunagrawal** [mbadolato/iTerm2-Color-Schemes#51]
When I look at a screenshot of a color scheme, I do not understand what the various rows and column values mean. For example, what does 37m and 1;37m mean and how are they different? What settings should I change to get a particular color scheme?
It would be nice to have this in the README.

**Comment by mbadolato** [comment]
The screenshots are generated from a script a lot of people use. They're for showing the colors in the scheme in their regular and bold versions and how they look comparatively with the other colors. You don't have to worry about setting any colors yourself. Simply import the scheme files and select the scheme you want, per the instructions in the README

**Comment by yan-kisen** [comment]
I'm still not sure about how to interpret the images.

Is **_m_** a unit of measurement? Which row/column represents the standard output for a color scheme?

Thanks!

**Comment by mbadolato** [comment]
They're just part of the code (escape codes or shell codes IIRC). The 1st column is basically what the theme is.

**Comment by sunaku** [comment]
@yan-kisen @varunagrawal learn about ANSI color escape sequences here: :books:
* http://wiki.bash-hackers.org/scripting/terminalcodes#foreground_coloring
* https://en.wikipedia.org/wiki/ANSI_escape_code#Colors

**Comment by mbadolato** [comment]
@sunaku :+1:
