### ISSUE TITLE
Batman scheme doesn't load

### ISSUE THREAD

**Issue by caseypatrickdriscoll** [mbadolato/iTerm2-Color-Schemes#52]
Using iTerm 2.1.4

Will investigate and hopefully do pull request. Other schemes load just fine. No obvious errors in file and nothing reported.

**Comment by mbadolato** [comment]
Could be the same issue as in #43. @lokson fixed a couple in #48 and #49 so this might just need to same solution. I don't know if i'll have time to investigate this week

**Comment by caseypatrickdriscoll** [comment]
It does work in the nightly. Not sure what the best path is here. I will leave it as is I think and close this comment. Others will hopefully find this post.

https://iterm2.com/downloads/nightly/#/section/home
