### ISSUE TITLE
Text gets invisible while running mocha

### ISSUE THREAD

**Issue by umayr** [mbadolato/iTerm2-Color-Schemes#59]
<img width="574" alt="screen shot 2015-12-05 at 18 48 57" src="https://cloud.githubusercontent.com/assets/3071948/11608065/254b2480-9b81-11e5-844d-edcbb7ea6a05.png">
As seen in the screenshot, some part of the text gets invisible for Solarized Dark theme. It's happening with gulp too.

My iTerm version is `2.1.4`.

**Comment by kevin-smets** [comment]
I fixed this in a gist of mine (I should launch a PRQ for this :) ) -> https://gist.github.com/kevin-smets/8568070#file-solarized-dark-fixed-itermcolors

The link fixes this: by default, the Ansi 8 Color is not readable on the set background for Solarized dark. This value has been replaced by the one from the Solarized high contrast theme.

**Comment by mbadolato** [comment]
> | should launch a PRQ for this

:+1:Please do!

**Comment by kevin-smets** [comment]
Done :)

Before:
<img width="212" alt="screen shot 2015-12-06 at 20 55 31" src="https://cloud.githubusercontent.com/assets/4222494/11615270/8775b52c-9c5c-11e5-8b6a-22efc4bd45b3.png">

After:
<img width="182" alt="screen shot 2015-12-06 at 20 55 58" src="https://cloud.githubusercontent.com/assets/4222494/11615271/87788c98-9c5c-11e5-88ee-7a564569a725.png">

**Comment by umayr** [comment]
@kevin-smets Awesome. But shouldn't it be any base colour rather than blue? Maybe `#586e75` or `#657b83`?

**Comment by kevin-smets** [comment]
@umayr good point, but that way it does not look like a highlight at all? It looks just like regular output. 

(This is `#657b83`)
<img width="199" alt="screen shot 2015-12-06 at 21 12 40" src="https://cloud.githubusercontent.com/assets/4222494/11615335/1d9e53e6-9c5e-11e5-8a5a-4da24dab46c6.png">

Just thought high contrast would be the nicest / closest match. Though the rest of the colors are indeed more grey like in Solarized Dark. But in the high contrast version, the highlight versions match the base colors more closely...

@mbadolato what do you think?

**Comment by kevin-smets** [comment]
Went with Base01, the darkest content color:

<img width="178" alt="screen shot 2015-12-06 at 21 29 04" src="https://cloud.githubusercontent.com/assets/4222494/11615413/85cdfbea-9c60-11e5-85ca-2711935eb3af.png">

Also adjusted the PRQ to this.

**Comment by mbadolato** [comment]
Either works for me; no particular preference. I may be one of the few people that doesn't use Solarized Dark :wink:

**Comment by umayr** [comment]
That looks really awesome. Thank you, @kevin-smets.

**Comment by kevin-smets** [comment]
No problem, now I can simplify my gist :D :dancers:

**Comment by eyaleizenberg** [comment]
I'm still facing this issue, what's the solution here?

<img width="904" alt="screen shot 2017-11-29 at 17 27 34" src="https://user-images.githubusercontent.com/1061345/33383279-963b3d66-d52b-11e7-9f27-17c841cb62c6.png">
<img width="865" alt="screen shot 2017-11-29 at 17 28 06" src="https://user-images.githubusercontent.com/1061345/33383281-966a8274-d52b-11e7-9dea-9428f3dd57db.png">

**Comment by mbadolato** [comment]
The issue was reverted (see #62). So other than changing the color manually yourself, or using a tweaked theme (or different altogether), this issue is likely to stay, if you're using something that has output in the affected color.  AFAIK, the Solarized theme in here matches the official standard, so it's not something with the theme itself, but rather with the output of the program
