### ISSUE TITLE
The Solarized Dark change should be reverted

### ISSUE THREAD

**Issue by jez** [mbadolato/iTerm2-Color-Schemes#62]
The changes introduced in #60 should be reverted. The official Solarized Colors (which people expect to install when selecting a theme titled "Solarized Dark") can be found in the [altercation/solarized][1] repo.

I can understand the motives of some people to use a different, more readable color for `Ansi 8 Color`. There has been much talk about this, to the point that some have even [reported it as a bug to altercation/solarized][2]. That's why my recommendation would not be to just revert #60. Instead, we should have a theme called "Solarized Dark" track the same `.itermcolors` as can be found in the [original repo][1], and we should introduce a new theme with a name like "Solarized Dark - Patched ANSI 8". This way people could choose, and not be surprised if they're expecting the defaults.

I'd be more than happy to open a PR for this if you'd support it.

[1]: https://github.com/altercation/solarized/tree/master/iterm2-colors-solarized
[2]: https://github.com/altercation/solarized/issues/220

**Comment by mbadolato** [comment]
Yeah that's a good idea and a PR would be most welcome. When that merged in I had actually begun thinking about that and to check on the "official" standards of Solarized Dark and it completely fell out of my head shortly thereafter. Thanks for the kick! :smile:
