### ISSUE TITLE
When importing iterm2 scheme, nothing happens

### ISSUE THREAD

**Issue by ozdv** [mbadolato/iTerm2-Color-Schemes#66]
version 10.11
Latest iTerm2
Trying to install schemes, but following instructions, it won't change the appearance of the iTerm window.  It shows the scheme I've imported, but clicking, does nothing.

When I click on a default scheme, it will change.

**Comment by mbadolato** [comment]
That sounds like an issue with your iTerm install. Once you've imported the themes, if you see them in the theme dropdown, selecting it should change what you see.

It could also be that you have multiple windows/tabs open and it isn't correctly determining which one to open. Use Cmd I->Colors->Color Presets to see if it changes an active window. If that doesn't work, try setting Cmd + -> Profile -> [your profile] -> Colors -> Color Presets and then open a new tab after you've closed the preferences window.

If neither of those two work, try reinstalling iTerm

**Comment by bent0b0x** [comment]
I am experiencing the same exact behavior as @Ozad. iTerm 2.1.4. I can import a preset, but when I select it from the menu of presets none of the colors on the preferences pane change, and nothing is reflected in the terminal.

**Comment by mbadolato** [comment]
@bent0b0x Did you try as I suggested as above?

**Comment by mbadolato** [comment]
Also, again, if you're doing it from CMD-, which is the global preset for a defined profile, it may not show up right away (especially if you have more than one window/tab open). DOing it from CMD-i is session specific so should work from there.

For the whole profile (CMD-,) changing it then opening new windows/tabs after that should reflect the new color.

Can either of you confirm this behavior?

**Comment by hugh-hefnerd** [comment]
I'm on OS X 10.11.3 and iTerm 2.1.4 and am seeing the same exact behavior. Whether I try and change colors in the session or profile tool there is no change in any of the window colors.

Logfile from iTerm located here.
[http://pastebin.com/hEpyPABm](url)

**Comment by mbadolato** [comment]
I don't have any other (or really any at all) suggestions for what could be causing this issue. I would suggest inquiring over in the iTerm repository where George may have some suggestions

**Comment by NeonMonk** [comment]
I'm having the same issue with Build 2.1.4, and the Batman color scheme. If I use the "preview" tool, it sets the scheme. If I select it from presets, either globally or in the profile, nothing happens. The ANSI colors don't change and there's no change in the terminal window. Nothing happens.

Here is the relevant console entry:
```

13/04/2016 7:05:40.535 pm iTerm[74298]: *** Assertion failure in -[PreferencePanel _loadPresetColors:], /Users/gnachman/v2/PreferencePanel.m:4002
13/04/2016 7:05:40.634 pm iTerm[74298]: An uncaught exception was raised
13/04/2016 7:05:40.634 pm iTerm[74298]: Missing color in existing dict
13/04/2016 7:05:40.636 pm iTerm[74298]: (
	0   CoreFoundation                      0x00007fff86f4d03c __exceptionPreprocess + 172
	1   libobjc.A.dylib                     0x00007fff90c1c76e objc_exception_throw + 43
	2   CoreFoundation                      0x00007fff86f4ce1a +[NSException raise:format:arguments:] + 106
	3   Foundation                          0x00007fff90ed199b -[NSAssertionHandler handleFailureInMethod:object:file:lineNumber:description:] + 195
	4   iTerm                               0x0000000107766ba1 -[PreferencePanel _loadPresetColors:] + 929
	5   libsystem_trace.dylib               0x00007fff8cbdbcd7 _os_activity_initiate + 75
	6   AppKit                              0x00007fff8af84eb1 -[NSApplication sendAction:to:from:] + 452
	7   AppKit                              0x00007fff8af84c4e -[NSMenuItem _corePerformAction] + 382
	8   AppKit                              0x00007fff8af8497c -[NSCarbonMenuImpl performActionWithHighlightingForItemAtIndex:] + 114
	9   libsystem_trace.dylib               0x00007fff8cbdbcd7 _os_activity_initiate + 75
	10  AppKit                              0x00007fff8b04bb00 -[NSMenu performActionForItemAtIndex:] + 131
	11  AppKit                              0x00007fff8b04ba66 -[NSMenu _internalPerformActionForItemAtIndex:] + 35
	12  AppKit                              0x00007fff8b04b8b2 -[NSCarbonMenuImpl _carbonCommandProcessEvent:handlerCallRef:] + 107
	13  AppKit                              0x00007fff8af6cd6b NSSLMMenuEventHandler + 724
	14  HIToolbox                           0x00007fff83c7ab6c _ZL23DispatchEventToHandlersP14EventTargetRecP14OpaqueEventRefP14HandlerCallRec + 1260
	15  HIToolbox                           0x00007fff83c79fae _ZL30SendEventToEventTargetInternalP14OpaqueEventRefP20OpaqueEventTargetRefP14HandlerCallRec + 386
	16  HIToolbox                           0x00007fff83c8fcb6 SendEventToEventTarget + 40
	17  HIToolbox                           0x00007fff83cc9f45 _ZL18SendHICommandEventjPK9HICommandjjhPKvP20OpaqueEventTargetRefS5_PP14OpaqueEventRef + 428
	18  HIToolbox                           0x00007fff83d07b8d SendMenuCommandWithContextAndModifiers + 59
	19  HIToolbox                           0x00007fff83d07b30 SendMenuItemSelectedEvent + 188
	20  HIToolbox                           0x00007fff83d07a09 _ZL19FinishMenuSelectionP13SelectionDataP10MenuResultS2_ + 96
	21  HIToolbox                           0x00007fff83ce3cc1 _ZL19PopUpMenuSelectCoreP8MenuData5PointdS1_tjPK4RecttjS4_S4_PK14__CFDictionaryPK10__CFStringPP13OpaqueMenuRefPt + 1877
	22  HIToolbox                           0x00007fff83ce2d74 _ZL26_HandlePopUpMenuSelection8P13OpaqueMenuRefP14OpaqueEventRefj5PointtjPK4RecttS6_S6_PK14__CFDictionaryPK10__CFStringPS0_Pt + 633
	23  HIToolbox                           0x00007fff83ce293b _HandlePopUpMenuSelectionWithDictionary + 287
	24  AppKit                              0x00007fff8b04171d _NSSLMPopUpCarbonMenu3 + 5810
	25  AppKit                              0x00007fff8b040059 _NSPopUpCarbonMenu3 + 153
	26  AppKit                              0x00007fff8b03ffb1 -[NSCarbonMenuImpl popUpMenu:atLocation:width:forView:withSelectedItem:withFont:withFlags:withOptions:] + 350
	27  AppKit                              0x00007fff8b0d3ec4 -[NSPopUpButtonCell trackMouse:inRect:ofView:untilMouseUp:] + 559
	28  AppKit                              0x00007fff8af97366 -[NSControl mouseDown:] + 714
	29  AppKit                              0x00007fff8b5012dc -[NSWindow _reallySendEvent:isDelayedEvent:] + 14125
	30  AppKit                              0x00007fff8ae90c86 -[NSWindow sendEvent:] + 470
	31  AppKit                              0x00007fff8ae8d212 -[NSApplication sendEvent:] + 2504
	32  iTerm                               0x00000001077a82cd -[iTermApplication sendEvent:] + 1597
	33  AppKit                              0x00007fff8adb6b68 -[NSApplication run] + 711
	34  AppKit                              0x00007fff8ad33244 NSApplicationMain + 1832
	35  iTerm                               0x00000001076f5950 main + 64
	36  iTerm                               0x00000001076f5904 start + 52
)

```

**Comment by PezCoder** [comment]
> Also, again, if you're doing it from CMD-, which is the global preset for a defined profile, it may not show up right away (especially if you have more than one window/tab open). DOing it from CMD-i is session specific so should work from there.

This worked for me, it changed the current opened sessions colors.. but after opening a new tab or even reloading iterm reverted back to a default colors..
When i launch iterm i see the color scheme colors for a split second & then it comes back to the some default blue color.. Could  it be zsh messing with it ?

**Comment by PezCoder** [comment]
I tried disabling zsh, & it worked. This is some issue with using zsh with iterm

**Comment by mbadolato** [comment]
Hmmm, interesting. I use ZSH and oh-my-zsh and have never had any issues. I wonder if there's a setting that causes it

**Comment by PezCoder** [comment]
I reinstall zsh & oh-my-zsh, now everything is working as expected, theme is loading perfectly. 😄

**Comment by PezCoder** [comment]
@ozdv you should give it a try

**Comment by PezCoder** [comment]
I had this in my zshrc that was causing the color overrides
```
# Base16 Shell (Needed for correct colors in base16 material theme)
# BASE16_SHELL="$HOME/.config/base16-shell/base16-material.dark.sh"
# BASE16_SHELL="$HOME/.config/oceanic-next-shell/oceanic-next.dark.sh"
# [[ -s $BASE16_SHELL ]] && source $BASE16_SHELL
```
I use to use this to get correct colors for my base 16 color scheme in vim.
