### ISSUE TITLE
Update website: iterm2colorschemes.com

### ISSUE THREAD

**Issue by crzidea** [mbadolato/iTerm2-Color-Schemes#78]
The website should be updated. I found one typo on http://iterm2colorschemes.com/

Website:

> The theme Mokokai Soda was found here.

But this line in the README is:

> The theme Monokai Soda was found here.

It's `Monokai`, not `Mokokai`.

**Comment by jdhmtl** [comment]
This no longer appears to be an issue.

**Comment by mbadolato** [comment]
It looks like it still is an issue; down in the Credits page (which is in the `gh-pages` branch and not the `README` file on `master`

**Comment by jdhmtl** [comment]
With #301 merged, this can now be closed
