### ISSUE TITLE
occur error when importing scheme

### ISSUE THREAD

**Issue by viix** [mbadolato/iTerm2-Color-Schemes#79]
<img width="532" alt="screen shot 2016-07-04 at 9 36 05 pm" src="https://cloud.githubusercontent.com/assets/8758499/16562379/6bffef0a-422f-11e6-9e37-0e96898a14dd.png">
iterm version: 3.0.0

**Comment by lokson** [comment]
Hi @viix 
Do you remember which theme?

**Comment by viix** [comment]
https://github.com/mbadolato/iTerm2-Color-Schemes/blob/master/schemes/Afterglow.itermcolors

**Comment by lokson** [comment]
@viix It seems to work on iTerm2 3.0.4. Update may solve the problem.

<img width="1218" alt="screen shot 2016-07-04 at 16 31 22" src="https://cloud.githubusercontent.com/assets/5403694/16563919/04069d74-4205-11e6-8dea-33deb1cdbd62.png">

**Comment by viix** [comment]
my fault, OK now.
thx @lokson
