### ISSUE TITLE
Explanation of Column Headers

### ISSUE THREAD

**Issue by StevenXL** [mbadolato/iTerm2-Color-Schemes#80]
Hello iTerm2-Color-Schemes theme,

I am not sure if this is the correct place to ask this question, but what do the columns mean for each screenshot? Is there a way to determine what "column" will be in effect on my system? 

Thanks for any input. I'd be happy to make a PR against the website and the README once I figure this out.

**Comment by mbadolato** [comment]
The left-most column is what the theme would look like. The remainder columns are showing affects of each color with the others. The screenshots aren't the most useful but they were pretty much the standard for what people have used so I continued with that trend when I put together these themes.
