### ISSUE TITLE
The color of the font is the same

### ISSUE THREAD

**Issue by summerGreenTea** [mbadolato/iTerm2-Color-Schemes#81]
i just do the things for install itermcolor theme in iterm2, but the background color of iterm2 was changed, the font color of iterms was  not changed. Anybody can tell me how to solve it ?  Thanks.

**Comment by im-martijn** [comment]
Same problem for me. CHanged to Jetbrains Darcula. Background changed to dark ok. All typography is in one color, which I assume it should not be.

**Comment by mbadolato** [comment]
Not sure why this would occur. Is it all themes or just one?

Also, from the command line try running ```unset LSCOLORS``` and see if it fixes the issue. If it doesn't you could try specifically setting it to something like ```export LSCOLORS=GxFxCxDxBxegedabagaced```.   If either of those work, add them to your .bashrc or .zshrc

**Comment by im-martijn** [comment]
Strange. Neither of those seem to work. I tried them both.



<https://www.instantmagazine.com>
+31 (0)20 3032822 <%2B31203032822>
martijn@instantmagazine.com
www.instantmagazine.com
www.twitter.com/instantmagazin
www.facebook.com/instantmagazine

<https://www.youtube.com/watch?v=UYu6Fv0Z3Vg>

2016-08-09 18:14 GMT+02:00 Mark Badolato <notifications@github.com>:

**Comment by shusso** [comment]
I have this in my ~/.profile
```
# Set CLICOLOR if you want Ansi Colors in iTerm2
export CLICOLOR=1

# Set colors to match iTerm2 Terminal Colors: Preferences-->Profiles-->Terminal-->"Report Terminal Type"
export TERM=xterm-256color
```

which seems to fix the issue for me

**Comment by renmax** [comment]
it seems that it has to be "export TERM=xterm-256color" in ~/.bash_profile.

**Comment by fyee** [comment]
but not work for me @shusso  @mbadolato

**Comment by Valcroca** [comment]
this is still happening
