### ISSUE TITLE
find the florescent light style theme

### ISSUE THREAD

**Issue by earthIsAPrisonIfYouNotAwareItCanNotOut** [mbadolato/iTerm2-Color-Schemes#85]
is there a theme like this:
<img width="791" alt="2016-08-06 11 00 58" src="https://cloud.githubusercontent.com/assets/16307328/17457400/b4d9c4d0-5c29-11e6-87d4-f18135a7b398.png">

**Comment by mbadolato** [comment]
None that I've come across. Not sure how iTerm would achieve the effect either. If you find something, let me know!
