### ISSUE TITLE
Worth working to build PuTTY version?

### ISSUE THREAD

**Issue by SpectralCoding** [mbadolato/iTerm2-Color-Schemes#98]
I originally found this list because there is a lack of PuTTY-compatible color schemes. I ended up using a tool to output the ANSI colors from the .itermcolors file and manually enter the values into the PuTTY colors interface. I could easily write a script to convert all the .itermcolors files here into .reg files which can create a PuTTY session template. These would live as another top-level directory named "putty"

Perhaps this is outside the scope of the repo. If there is interest, let me know and I will do the work and submit a pull request.

Edit: Would look roughly like [this gist](https://gist.github.com/SpectralCoding/5a8e847272ad060e68a936b039fa97f2) minus the verbose comments at the bottom.

**Comment by mbadolato** [comment]
The repo has been morphing into a resource for all sorts of versions in addition to iTerm. If you'd like to contribute a putty version, it would be most welcome!

Thanks!

**Comment by SpectralCoding** [comment]
Submitted Pull Request #99: Add PuTTY color schemes and related support files.

**Comment by mbadolato** [comment]
Got it, thanks!
